config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get '/items', to: 'items#index'
  #post '/items', to: 'items#create'

  root to: 'items#index'
  get '/admin/users_count', to: 'admin#users_count'

  resources :items do #, only: %i[index create]
    get :upvote, on: :member          # с id
    get :expensive, on: :collection   # без  id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true # optional: true - на время чтобы можно было создать Cart без User
  #has_and_belongs_to_many :items
  has_many :positions
  has_many :items, through: :positions
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :price, numericality: { greater_than: 0 }
  validates :name, presence: true
  #has_and_belongs_to_many :carts
  has_many :positions
  has_many :carts, through: :positions
  has_many :comments, as: :commentable
  has_one :image, as: :imageable
  has_and_belongs_to_many :orders

=begin
  after_initialize { p 'init'}
  after_save       { p 'save' }
  after_create     { p 'create' }
  after_update     { p 'update' }
  after_destroy    { p 'destroy' }
=end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :items

  def calculate_total
    write_attribute :total, items.map(&:price).inject(:+)
  end
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart, dependent: :destroy # удаляет зависимые данные тоже, т.е. из card
  has_many :orders, dependent: :destroy
  has_many :comments
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :admin?
  #layout 'admin' - для всех экшенов

  def users_count
    @users_count = User.count
    render layout: 'admin'   # layout для конкретного экшена
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def render_403
    render file: 'public/403.html', status: :forbidden
  end

  def render_404
    render file: 'public/404.html', status: :not_found
  end

  def admin?
    render_403 unless params[:admin]
    #render json: "Access denied", status: :forbidden unless params[:admin]
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #layout false

  # запишем данные из консоли
  skip_before_action :verify_authenticity_token # пропускает токен, что бы его не вводить
  before_action :find_item, only: %i[show edit update destroy upvote]
  before_action :admin?, only: %i[edit]
  after_action :show_info, only: %i[index]

  def index
    @items = Item.all.order :id # можно писать условия Item.where('price > 200 OR votes_count >= 2')
    @items = @items.includes(:image) # запросом выбирает сразу все фото, без этого на каждую фотку 1 запрос
    #render body: @items.map { |i| "#{i.name}: #{i.price}" }
  end

  def create
    @item = Item.create(items_params)
    if @item.persisted?
      flash[:success] = 'Item was saved'
      redirect_to root_path #items_path
    else
      flash.now[:error] = 'Plase fill all fields correctly'
      render :new
      #render json: item.errors, status: :unprocessable_entity
    end
  end

  def new
    @item = Item.new
  end
=begin
  def show
    render body: 'Page not found', status: 404 unless @item
  end

  def edit
    render body: 'Page not found', status: 404 unless @item
  end
=end
  def update
    if @item.update(items_params)
      flash[:success] = 'Item was updated'
      redirect_to item_path
    else
      flash.now[:error] = 'Plase fill all fields correctly'
      render json: item.errors, status: :unprocessable_entity
      #render body: 'Page not found', status: :unprocessable_entity
    end
  end

  def destroy
    if @item.destroy.destroyed?
      flash[:success] = 'Item was deleted'
      render json: { success: true } #redirect_to root_path #items_path # или '/items'
    else
      flash[:error] = 'Item wasn^t deleted'
      render json: item.errors, status: :unprocessable_entity
      #render body: 'Page not found', status: :unprocessable_entity
    end
  end

  def upvote
    @item.increment! :votes_count
    redirect_to items_path
  end

  def expensive
    @items = Item.where('price > 1000')
    render :index
  end

  private

  def items_params
    params.require(:item).permit(:name, :price, :desc)
  end
  
  def find_item
    @item = Item.where(id: params[:id]).first
    render_404 unless @item
  end

  def show_info
    puts 'Index end point'
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def urls_to_content(str)
    str.gsub!(%r{https://[^\s<]+}) do |url|
      if url[/(?:png|jpe?g|gif|svg])$/]
      "<img src='#{url}' width='100'; />"
      else
        #"<a href='#{url}'>#{url}<a/>"
        "<a href='#{url}' target='_blank'>Link to info<a/>" # target='_blank' открывает новую вкладку
      end
    end
    str.html_safe
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/users_count.html.erb
<div style="margin: 0 auto">
  <h3>Count users: <%= @users_count %> on this site.</h3>
</div>

app/views/include/main/_notification.html.erb
<% if notice %>
  <p class="notice alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/items/edit.html.erb
<div class="col-sm-12 my-auto">
<h2>Edit <%= @item.name.camelize %></h2>

  <%= simple_form_for @item do |f| %>
    <div class="form-group row">
      <div class="col-sm-10">
        <%= f.input :name, input_html: {class: "form-control form-control-sm",
                                        id: "colFormLabelSm"} %>
      </div>
      <div class="col-sm-10">
        <%= f.input :price, input_html: {class: "form-control form-control-sm",
                                       id: "colFormLabelSm"}, required: true %>
      </div>
      <div class="col-sm-10">
        <%= f.input :desc, label: t("item.desc"),
            input_html: { class: "form-control form-control-sm",
                          id: "colFormLabelSm"} %>
      </div>
      <div class="col-sm-10">
        <%= f.button :submit, class: "btn btn-secondary",
                     style: "margin-top: 15px"%>
      </div>
    </div>
  <% end %>

<%= render partial: "shared/email" %>
</div>

app/views/items/index.html.erb
<h2>All Item</h2>

<% unless @items.empty? %>
  <table class="table table-hover table-dark">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Description</th>
        <th scope="col">Rating</th>
        <th scope="col">Image</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <% @items.each do |item| %>

      <!--   <li><%= link_to item.name, "/items/#{item.id}" %></li>
    Или вариант ниже
 -->
      <tbody>
        <tr data-item_id="<%= item.id %>">
          <th scope="col"><%= item.id %></th>
          <th scope="col"><%= link_to item.name.camelize, item_path(item), class: "text-info" %></th>
          <th scope="col"><%= item.price %></th>
          <th scope="col"><%= item.desc %></th>
          <th scope="col"><%= item.votes_count %> &nbsp; <%= link_to "+", upvote_item_path(item), class: "text-info" %></th>
          <th scope="col"><%= !item.image.nil? ? image_tag(item.image.file, width: '30px', height: '30px') : 'no img' %></th>
 <!--
          <th scope="col"><%= button_to "delete", item_path(item),
                                        method: :delete,
                                        class: "deleteAction" %></th>
-->
          <th class="deleteAction">delete</th>
        </tr>
      </tbody>
    <% end %>
  </table>

  <br/>
  <div class="btn-toolbar mb-3" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group mr-2" role="group" aria-label="First group">
      <%= button_to 'create item', new_item_path,
                    method: :get,
                    class: "btn btn-secondary",
                    style: "margin-right: 15px"%>
      <%= button_to 'only expensive', expensive_items_path,
                    method: :get,
                    class: "btn btn-secondary",
                    style: "margin-right: 15px"%>
      <%= button_to 'index', items_path,
                    method: :get,
                    class: "btn btn-secondary",
                    style: "margin-right: 15px"%>
      <%= button_to 'admin panel', admin_users_count_path,
                    method: :get,
                    class: "btn btn-secondary",
                    style: "margin-right: 15px"%>
    </div>
  </div>
<% else %>
  <h2 style="color: #B00100; margin: 0 auto">No Item</h2>
  <%= button_to 'new item', new_item_path, method: :get %>
<% end %>

<%= render :partial => "shared/email" %>

app/views/items/new.html.erb
<div class="col-sm-12 my-auto">
  <h2>Create new Item</h2>

  <%= simple_form_for @item do |f| %>
    <div class="form-group row">
      <div class="col-sm-10">
        <%= f.input :name, input_html: { class: "form-control form-control-sm",
                                         id: "colFormLabelSm"} %>
      </div>
      <div class="col-sm-10">
        <%= f.input :price, input_html: { class: "form-control form-control-sm",
                                          id: "colFormLabelSm"}, required: true %>
      </div>
        <div class="col-sm-10">
          <%= f.input :desc, label: t("item.desc"),
                      input_html: { class: "form-control form-control-sm",
                                    id: "colFormLabelSm"} %>
        </div>
      <div class="col-sm-10">
        <%= f.button :submit, class: "btn btn-secondary",
                      style: "margin-top: 15px"%>
      </div>
    </div>
  <% end %>

  <%= render partial: "shared/email" %>
</div>

app/views/items/show.html.erb
<!-- haml
%h2 Show Item

%h4= @item.name.upcase

%ul
  %li Price #{@item.price}
  %li Weight #{@item.weight}
  %li Description #{urls_to_content(@item.desc)}
  %li Link: #{urls_to_content('https://ru.wikipedia.org/wiki/%D0%A0%D1%83%D0%B1%D0%B8%D0%BD')}

%br

= button_to "edit #{@item.name}", edit_item_path, method: :get
= button_to "delete", item_path(@item), method: :delete
= button_to "index", items_path, method: :get

= render partial: "shared/email"

-#      .erb
-->

<h2>Show Item</h2>

<h4><%= @item.name.upcase %></h4>

<ul class="list-group">
  <li class="list-group-item list-group-item-dark">
    Price <%= @item.price %> $
  </li>
  <li class="list-group-item list-group-item-dark">
    Weight <%= @item.weight %> kg
  </li>
  <li class="list-group-item list-group-item-dark">
    Description <%= urls_to_content(@item.desc) %>
  </li>
  <li>Link: <%= urls_to_content('https://ru.wikipedia.org/wiki/%D0%A0%D1%83%D0%B1%D0%B8%D0%BD') %></li>
</ul>

<br/>
<div class="btn-toolbar mb-3" role="toolbar" aria-label="Toolbar with button groups">
  <div class="btn-group mr-2" role="group" aria-label="First group">
  <%= button_to "edit #{@item.name}", edit_item_path,
                method: :get,
                class: "btn btn-secondary",
                style: "margin-right: 15px"%>
  <%= button_to "delete", item_path(@item),
                method: :delete,
                class: "btn btn-secondary",
                style: "margin-right: 15px"%>
  <%= button_to "index", items_path,
                method: :get,
                class: "btn btn-secondary",
                style: "margin-right: 15px"%>
  </div>
</div>
<%= render partial: "shared/email" %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="jumbotron vertical-center">
    <div class="container">
      <h2 style="color: #B00100">Admin panel</h2>
      <%= yield %>
      <% render partial: "shared/email" %>
    </div>
  </div>
  </body>

  <footer>
    <p>Здесь футер... По всем вопросам писать на почту...</p>
  </footer>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('fav.png') %>
  </head>

  <body>

  <!-- devise-->
    <%= render "include/auth/auth_header" %>
  <!-- devise-->

  <div class="jumbotron vertical-center">
    <div class="container">
      <h2 style="color: #B00100">User panel</h2>
      <%= render 'include/main/notification' %>
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/shared/_email.html.erb
<div class="email" style="font-size: 12px; font-weight: bold; margin: 20px">
  <p>Вопросы пишите на почту </p>
  <%= mail_to 'qqq@qq.com', 'Qqq@Qq.com', {style:'color: black'} %>
</div>